all :

1 :
	gcc 1_2798.c
	./a.out
	rm a.out
2 :
	gcc 2_2231.c
	./a.out
	rm a.out
3 :
	gcc 3_7568.c
	./a.out
	rm a.out
4 :
	gcc 4_1018.c
	./a.out
	rm a.out
5 :
	gcc 5_1436.c
	./a.out
	rm a.out
5p :
	python 5_1436.py
