all :

1 :
	gcc 1_10818.c
	./a.out
	rm a.out
2 :
	gcc 2_2562.c
	./a.out
	rm a.out
3 :
	gcc 3_2577.c
	./a.out
	rm a.out
4 :
	gcc 4_3052.c
	./a.out
	rm a.out
5 :
	gcc 5_1546.c
	./a.out
	rm a.out
6 :
	gcc 6_8958.c -Wall -Wextra -Werror
	./a.out
	rm a.out
7 :
	gcc 7_4344.c -Wall -Wextra -Werror
	./a.out
	rm a.out