all :

1 :
	gcc 1_2739.c
	./a.out
	rm a.out
2 :
	gcc 2_10950.c
	./a.out
	rm a.out
3 :
	gcc 3_8393.c
	./a.out
	rm a.out
4 :
	gcc 4_15552.c
	./a.out
	rm a.out
5 :
	gcc 5_2741.c
	./a.out
	rm a.out
6 :
	gcc 6_2742.c
	./a.out
	rm a.out
7 :
	gcc 7_11021.c
	./a.out
	rm a.out
8 :
	gcc 8_11022.c
	./a.out
	rm a.out
9 :
	gcc 9_2438.c
	./a.out
	rm a.out
10 :
	gcc 10_2439.c
	./a.out
	rm a.out
11 :
	gcc 11_10871.c
	./a.out
	rm a.out
12 :
	gcc 12_10952.c
	./a.out
	rm a.out
13 :
	gcc 13_10951.c
	./a.out
	rm a.out
14 :
	gcc 14_1110.c
	./a.out
	rm a.out

25304 :
	python 25304.py