all :

1 :
	gcc 1_1712.c
	./a.out
	rm a.out
2 :
	gcc 2_2292.c
	./a.out
	rm a.out
3 :
	gcc 3_1193.c
	./a.out
	rm a.out
4 :
	gcc 4_2869.c
	./a.out
	rm a.out
5 :
	gcc 5_10250.c
	./a.out
	rm a.out
6 :
	gcc 6_2775.c
	./a.out
	rm a.out
7 :
	gcc 7_2839.c
	./a.out
	rm a.out
8 :
	gcc 8_10757.c
	./a.out
	rm a.out