all :

1 :
	gcc 1_1330.c
	./a.out
	rm a.out
2 :
	gcc 2_9498.c
	./a.out
	rm a.out
3 :
	gcc 3_2753.c
	./a.out
	rm a.out
4 :
	gcc 4_14681.c
	./a.out
	rm a.out
5 :
	gcc 5_2884.c
	./a.out
	rm a.out
6 :
	gcc 6_2525.c
	./a.out
	rm a.out
7 :
	gcc 7_2480.c
	./a.out
	rm a.out