all : 1 2 3 4 5 6 7 8 9 10 11 12 13 14

1 :
		gcc 1_2557.c
		./a.out
		rm a.out
2 :
		gcc 2_10718.c
		./a.out
		rm a.out
3 :
		gcc 3_10171.c
		./a.out
		rm a.out
4 :
		gcc 4_10172.c
		./a.out
		rm a.out
5 :
		gcc 5_1000.c
		./a.out
		rm a.out
6 :
		gcc 6_1001.c
		./a.out
		rm a.out
7 :
		gcc 7_10998.c
		./a.out
		rm a.out
8 :
		gcc 8_1008.c
		./a.out
		rm a.out
9 :
		gcc 9_10869.c
		./a.out
		rm a.out
10 :
		gcc 10_10926.c
		./a.out
		rm a.out
11 :
		gcc 11_18108.c
		./a.out
		rm a.out
12 :
		gcc 12_10430.c
		./a.out
		rm a.out
13 :
		gcc 13_2588.c
		./a.out
		rm a.out
14 :
		gcc 14_25083.c
		./a.out
		rm a.out

15 :
		python 3003.py