all :

1 :
	gcc 1_11654.c -Wall -Werror -Wextra
	./a.out
	rm a.out
2 :
	gcc 2_11720.c -Wall -Werror -Wextra
	./a.out
	rm a.out
3 :
	gcc 3_10809.c -Wall -Werror -Wextra
	./a.out
	rm a.out
4 :
	gcc 4_2675.c
	./a.out
5 :
	gcc 5_1157.c
	./a.out
	rm a.out
6 :
	gcc 6_1152.c
	./a.out
	rm a.out
7 :
	gcc 7_2908.c
	./a.out
	rm a.out
8 :
	gcc 8_5622.c
	./a.out
	rm a.out
9 :
	gcc 9_2941.c
	./a.out
	rm a.out
10 :
	gcc 10_1316.c
	./a.out
	rm a.out