all :

1 :
	gcc 1_1978.c
	./a.out
	rm a.out
2 :
	gcc 2_2581.c
	./a.out
	rm a.out
3 :
	gcc 3_11653.c
	./a.out
	rm a.out
4 :
	gcc 4_1929.c
	./a.out
	rm a.out
5 :
	gcc 5_4948.c
	./a.out
	rm a.out
6 :
	gcc 6_9020.c
	./a.out
	rm a.out